/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;
import java.text.*;
import java.io.File;
import java.io.*;
import java.util.*;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import java.io.IOException;
import org.apache.commons.net.ftp.FTPClient;
import java.util.Date;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author m1415425
 */
public class ArquivoTela extends javax.swing.JFrame {
    static final int TAMANHO_BUFFER = 20480; // 20kb
    private volatile Thread runner;
    FTPClient ftp = new FTPClient();

    
    /**
     * Creates new form ArquivoTela
     */
    public ArquivoTela()   {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conectar = new java.awt.Button();
        Desconectar = new java.awt.Button();
        Status = new java.awt.Label();
        TipoStatus = new java.awt.Label();
        ArqEnviadosFTP = new java.awt.TextArea();
        DominioText = new java.awt.TextField();
        LoginText = new java.awt.TextField();
        LoginLabel = new java.awt.Label();
        SenhaLabel = new java.awt.Label();
        DominioLabel = new java.awt.Label();
        ArqDiretorioText = new java.awt.TextField();
        ArqSalvarDiretorioText = new java.awt.TextField();
        ArqDiretorioLabel = new java.awt.Label();
        ArqSalvarDiretorioLabel = new java.awt.Label();
        EnviarBotao = new java.awt.Button();
        Exemple1Label = new java.awt.Label();
        Exemple2Label = new java.awt.Label();
        EnvioLabel = new java.awt.Label();
        EnvioProxLabel = new java.awt.Label();
        StatusEnvio = new java.awt.Label();
        SenhaFtp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);

        Conectar.setLabel("Connectar");
        Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarActionPerformed(evt);
            }
        });

        Desconectar.setActionCommand("Desconectar");
        Desconectar.setEnabled(false);
        Desconectar.setLabel("Desconectar");
        Desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesconectarActionPerformed(evt);
            }
        });

        Status.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Status.setText("Status: ");

        TipoStatus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TipoStatus.setName("TipoStatus"); // NOI18N
        TipoStatus.setText("Offiline");

        ArqEnviadosFTP.setEditable(false);

        DominioText.setText("10.52.1.102");
        DominioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DominioTextActionPerformed(evt);
            }
        });

        LoginText.setName(""); // NOI18N
        LoginText.setText("tempftp");

        LoginLabel.setText("Login: ");

        SenhaLabel.setText("Senha: ");

        DominioLabel.setText("Dominio: ");

        ArqDiretorioText.setEnabled(false);
        ArqDiretorioText.setText("C:\\\\Users\\\\m1415425\\\\Documents\\\\Novapasta");

        ArqSalvarDiretorioText.setEnabled(false);
        ArqSalvarDiretorioText.setText("C:\\\\Users\\\\m1415425\\\\Documents\\\\Zip\\\\Arquivo.zip");

        ArqDiretorioLabel.setText("Direotiro do Arquivos: ");

        ArqSalvarDiretorioLabel.setText("Diretorio Salvar Arquivo.zip");

        EnviarBotao.setEnabled(false);
        EnviarBotao.setLabel("Enviar");
        EnviarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarBotaoActionPerformed(evt);
            }
        });

        Exemple1Label.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        Exemple1Label.setText("Exemplo: C:\\\\Users\\\\m1415425\\\\Documents\\\\Zip\\\\Arquivo.zip");

        Exemple2Label.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        Exemple2Label.setText("Exemplo: C:\\\\Users\\\\m1415425\\\\Documents\\\\Novapasta");

        EnvioLabel.setText("Horário execução: --: --:--");

        EnvioProxLabel.setText("Próxima execução: --:--:-- ");

        StatusEnvio.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        StatusEnvio.setText("Status Envio: ");

        SenhaFtp.setText("comdata");
        SenhaFtp.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DominioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ArqDiretorioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(ArqDiretorioText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DominioText, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LoginText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SenhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SenhaFtp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TipoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(Exemple2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EnvioProxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EnvioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Desconectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ArqEnviadosFTP, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(StatusEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(EnviarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ArqSalvarDiretorioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArqSalvarDiretorioText, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exemple1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DominioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DominioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SenhaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ArqDiretorioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ArqDiretorioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(Exemple2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SenhaFtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ArqSalvarDiretorioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArqSalvarDiretorioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(Exemple1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EnvioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(EnvioProxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Conectar, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(Desconectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EnviarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ArqEnviadosFTP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        Conectar.getAccessibleContext().setAccessibleName("Conectar");
        Status.getAccessibleContext().setAccessibleName("Status");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarActionPerformed
        try{
 
        String dominio="",login="",senha="";
        dominio=DominioText.getText();
        login=LoginText.getText();
        senha=SenhaFtp.getText();        
        DominioText.setEnabled(false);
        LoginText.setEnabled(false);
        SenhaFtp.setEnabled(false);
        ftp.connect(dominio);
        ftp.login(login,senha);
        if(ftp.isConnected())
            TipoStatus.setText("Online");
        else 
            TipoStatus.setText("Offiline");
        Conectar.setEnabled(false);
        ArqDiretorioText.setEnabled(true);
        ArqSalvarDiretorioText.setEnabled(true);
        EnviarBotao.setEnabled(true);
        Desconectar.setEnabled(true);
    }catch(IOException f){
        JOptionPane.showMessageDialog(null, "CAMPO FALTANTE!", "ALERTA!", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ConectarActionPerformed

    private void EnviarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarBotaoActionPerformed
        if (runner != null) 
            return;
        runner = new Thread(this::loop);
        runner.start();
    }//GEN-LAST:event_EnviarBotaoActionPerformed

    private void DesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesconectarActionPerformed
runner = null;

        ArqEnviadosFTP.setText("");
        StatusEnvio.setText("Status Envio: ");
        StatusEnvio.setForeground(Color.black);
        TipoStatus.setText("Offiline");
        ArqDiretorioText.setEnabled(false);
        Desconectar.setEnabled(false);
        ArqSalvarDiretorioText.setEnabled(false);
        DominioText.setEnabled(true);
        LoginText.setEnabled(true);
        SenhaFtp.setEnabled(true);
        EnvioLabel.setText("Horário execução: --: --:--");
        EnvioProxLabel.setText("Próxima execução: --: --:--");
        Conectar.setEnabled(true);
    }//GEN-LAST:event_DesconectarActionPerformed

    private void DominioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DominioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DominioTextActionPerformed

    
     private static void compactarParaZip(String arqSaida, File[] arqEntrada, int tam) throws IOException {
        FileOutputStream destino;
        ZipOutputStream saida;
        try {
            destino = new FileOutputStream(new File(arqSaida));
            saida = new ZipOutputStream(new BufferedOutputStream(destino));
            for (int i = 0; i < tam; i++) {
                add(arqEntrada[i].toString(), saida);
            }
            saida.close();
        } catch (IOException e) {
            throw new IOException(e.getMessage());
        }
    }

    private static void add(String arquivo, ZipOutputStream saida) throws IOException {
        int cont;
        byte[] dados = new byte[TAMANHO_BUFFER];
        File file = new File(arquivo);
        BufferedInputStream origem = new BufferedInputStream(new FileInputStream(file), TAMANHO_BUFFER);
        ZipEntry entry = new ZipEntry(file.getName());
        saida.putNextEntry(entry);
        while ((cont = origem.read(dados, 0, TAMANHO_BUFFER)) != -1) {
            saida.write(dados, 0, cont);
        }
        origem.close();
    }
    
    private void loop() {
        try {
            
                long tempoDeEspera = 900000; //15 minutos
                String diretorioLocal, diretorioSalvar;
                diretorioLocal = ArqDiretorioText.getText();
                diretorioSalvar = ArqSalvarDiretorioText.getText();
                ArqDiretorioText.setEnabled(false);
                ArqSalvarDiretorioText.setEnabled(false);
                EnviarBotao.setEnabled(false);
                ArqEnviadosFTP.setText("");
                while (runner == Thread.currentThread()) {
                FileInputStream arqEnviar = new FileInputStream(diretorioSalvar);
                File arquivos[];

                File diretorio = new File(diretorioLocal);
                arquivos = diretorio.listFiles();
               
                ArqEnviadosFTP.append("Quantidade de Arquvios Encontrados: " + arquivos.length + "\n");
                for (File arquivo : arquivos) 
                    ArqEnviadosFTP.append(arquivo.getName() + "\n");
                
                compactarParaZip(diretorioSalvar, arquivos, arquivos.length);
                
                if (ftp.storeFile("Arquivo.zip", arqEnviar)) {
                    StatusEnvio.setText("Status Envio: Enviado!");
                    StatusEnvio.setForeground(Color.green);
                } else {
                    StatusEnvio.setText("Status Envio: Não Enviado!");
                    StatusEnvio.setForeground(Color.red);
                }
                    Date date = new Date();
                    Calendar data = Calendar.getInstance();
                    EnvioLabel.setText("Horário execução: " + date);
                    GregorianCalendar gc = new java.util.GregorianCalendar();
                    gc.add(Calendar.MINUTE, 15);
                    EnvioProxLabel.setText("Próxima execução: " + gc.getTime());
                    DateFormat formatoData = new SimpleDateFormat("dd-MM-yyyy_HH-mm");
                    String caminho = "C:\\Users\\m1415425\\Documents\\Zip\\" + formatoData.format(data.getTime()) + "_log.txt";

                File arquivoEscrita = new File(caminho);
                try (FileWriter fileWrite = new FileWriter(arquivoEscrita) //arquivo para escrita
                ) {
                    for (File arquivo : arquivos) {
                        fileWrite.write(arquivo.getName()+"\n");
                    }
                }
                
                Thread.sleep(tempoDeEspera);
            }

        } catch (Exception e) {

        }
    }
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArquivoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArquivoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArquivoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArquivoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label ArqDiretorioLabel;
    private java.awt.TextField ArqDiretorioText;
    private java.awt.TextArea ArqEnviadosFTP;
    private java.awt.Label ArqSalvarDiretorioLabel;
    private java.awt.TextField ArqSalvarDiretorioText;
    private java.awt.Button Conectar;
    private java.awt.Button Desconectar;
    private java.awt.Label DominioLabel;
    private java.awt.TextField DominioText;
    private java.awt.Button EnviarBotao;
    private java.awt.Label EnvioLabel;
    private java.awt.Label EnvioProxLabel;
    private java.awt.Label Exemple1Label;
    private java.awt.Label Exemple2Label;
    private java.awt.Label LoginLabel;
    private java.awt.TextField LoginText;
    private javax.swing.JPasswordField SenhaFtp;
    private java.awt.Label SenhaLabel;
    private java.awt.Label Status;
    private java.awt.Label StatusEnvio;
    private java.awt.Label TipoStatus;
    // End of variables declaration//GEN-END:variables
}
